#!/usr/bin/env python3
"""Generate every harness-native manifest + doc catalog from one source.

Source of truth:
  - plugin.source.json          repo-level metadata
  - skills/<name>/SKILL.md       per-skill name + description (YAML frontmatter)

Generated (DO NOT hand-edit):
  - .claude-plugin/plugin.json          Claude Code plugin manifest
  - .claude-plugin/marketplace.json     Claude Code marketplace registry
  - .codex-plugin/plugin.json           Codex CLI plugin manifest
  - .agents/plugins/marketplace.json    Codex CLI marketplace registry
  - SKILLS table inside README.md / AGENTS.md / CLAUDE.md (between markers)

Usage:
  python scripts/generate.py          write all artifacts
  python scripts/generate.py --check  fail (exit 1) if any artifact is stale
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MARK_START = "<!-- SKILLS:START (generated by scripts/generate.py — do not edit) -->"
MARK_END = "<!-- SKILLS:END -->"


def parse_frontmatter(md_path):
    """Return {name, description} from a SKILL.md YAML frontmatter block.

    Minimal single-line key:value parser — no pyyaml dependency. ponytail:
    these skills only need name+description, both single-line; upgrade to a
    real YAML parser only if a skill needs multi-line/nested frontmatter.
    """
    text = md_path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise SystemExit(f"ERROR: {md_path.relative_to(ROOT)} has no YAML frontmatter")
    body = text.split("---", 2)
    if len(body) < 3:
        raise SystemExit(f"ERROR: {md_path.relative_to(ROOT)} frontmatter block not closed")
    fields = {}
    for line in body[1].splitlines():
        if ":" in line and not line.startswith((" ", "\t", "#")):
            key, _, val = line.partition(":")
            fields[key.strip()] = val.strip()
    for req in ("name", "description"):
        if not fields.get(req):
            raise SystemExit(f"ERROR: {md_path.relative_to(ROOT)} frontmatter missing '{req}'")
    return {"name": fields["name"], "description": fields["description"]}


def load_skills():
    skills = []
    for skill_md in sorted(ROOT.glob("skills/*/SKILL.md")):
        fm = parse_frontmatter(skill_md)
        dirname = skill_md.parent.name
        if fm["name"] != dirname:
            raise SystemExit(
                f"ERROR: {skill_md.relative_to(ROOT)} name '{fm['name']}' "
                f"!= directory '{dirname}'"
            )
        skills.append(fm)
    return skills


def dumps(obj):
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def build_artifacts(src, skills):
    """Return {relative_path: content_string} for every generated file."""
    keywords = src["keywords"]
    author_obj = src["owner"]
    author_str = f'{author_obj["name"]} <{author_obj["email"]}>'
    short = src["description"].split(".")[0] + "."

    claude_plugin = {
        "name": src["name"],
        "version": src["version"],
        "description": src["description"],
        "author": author_obj,
        "homepage": src["homepage"],
        "repository": src["repository"],
        "license": src["license"],
        "keywords": keywords,
    }
    claude_marketplace = {
        "name": src["name"],
        "owner": src["owner"],
        "metadata": {"description": src["description"], "version": src["version"]},
        "plugins": [
            {
                "name": src["name"],
                "source": "./",
                "description": src["description"],
                "category": src["category"],
                "keywords": keywords,
            }
        ],
    }
    codex_plugin = {
        "name": src["name"],
        "version": src["version"],
        "description": src["description"],
        "author": author_str,
        "homepage": src["homepage"],
        "repository": src["repository"],
        "license": src["license"],
        "keywords": keywords,
        "interface": {"displayName": src["name"], "shortDescription": short},
        "skills": "./skills",
    }
    codex_marketplace = {
        "name": src["name"],
        "interface": {"displayName": src["name"], "shortDescription": short},
        "plugins": [
            {
                "name": src["name"],
                "source": {"source": "local", "path": "./"},
                "category": src["category"],
                "description": src["description"],
            }
        ],
    }

    artifacts = {
        ".claude-plugin/plugin.json": dumps(claude_plugin),
        ".claude-plugin/marketplace.json": dumps(claude_marketplace),
        ".codex-plugin/plugin.json": dumps(codex_plugin),
        ".agents/plugins/marketplace.json": dumps(codex_marketplace),
    }

    catalog = skills_table(skills)
    for doc in ("README.md", "AGENTS.md"):
        p = ROOT / doc
        if not p.exists():
            continue
        artifacts[doc] = inject(p.read_text(encoding="utf-8"), catalog, doc)
    # CLAUDE.md is a byte-for-byte copy of AGENTS.md: Codex reads AGENTS.md,
    # Claude reads CLAUDE.md, and both must carry identical guidance.
    if "AGENTS.md" in artifacts:
        artifacts["CLAUDE.md"] = artifacts["AGENTS.md"]
    return artifacts


def skills_table(skills):
    lines = [MARK_START, ""]
    if skills:
        lines += ["| Skill | What it does |", "| --- | --- |"]
        for s in skills:
            first = s["description"].split(". ")[0].rstrip(".") + "."
            lines.append(f"| `{s['name']}` | {first} |")
    else:
        lines.append("_No skills yet. Add `skills/<name>/SKILL.md` and run `python scripts/generate.py`._")
    lines += ["", MARK_END]
    return "\n".join(lines)


def inject(text, catalog, doc):
    if MARK_START not in text or MARK_END not in text:
        raise SystemExit(
            f"ERROR: {doc} is missing the {MARK_START} / {MARK_END} marker pair"
        )
    pre = text.split(MARK_START)[0]
    post = text.split(MARK_END, 1)[1]
    return pre + catalog + post


def main():
    check = "--check" in sys.argv
    src = json.loads((ROOT / "plugin.source.json").read_text(encoding="utf-8"))
    skills = load_skills()
    artifacts = build_artifacts(src, skills)

    stale = []
    for rel, content in artifacts.items():
        path = ROOT / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(rel)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    # Enforce AGENTS.md and CLAUDE.md are byte-identical on disk.
    agents_md, claude_md = ROOT / "AGENTS.md", ROOT / "CLAUDE.md"
    if agents_md.exists() and claude_md.exists():
        if agents_md.read_bytes() != claude_md.read_bytes():
            print("ERROR: AGENTS.md and CLAUDE.md are not byte-identical "
                  "(run `python scripts/generate.py`)")
            sys.exit(1)

    if check:
        if stale:
            print("STALE (run `python scripts/generate.py`):")
            for rel in stale:
                print(f"  - {rel}")
            sys.exit(1)
        print(f"OK: {len(artifacts)} artifacts up to date ({len(skills)} skills)")
    else:
        print(f"Generated {len(artifacts)} artifacts from {len(skills)} skills:")
        for rel in artifacts:
            flag = " (updated)" if rel in stale else ""
            print(f"  - {rel}{flag}")


if __name__ == "__main__":
    main()
